import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header/Header'
import DashboardNavbar from './components/DashboardNavbar/dashboardNavbar'

const inter = Inter({ subsets: ['latin'] })
// export const metadata = {
//       title: 'Create Next App',
//       description: 'Generated by create next app',
// }

export default function RootLayout({ children, isAdmin }) {
      return (
            <html lang="en">
                  <body className={inter.className}>
                        <Header />
                        {children}
                  </body>
            </html>
      )
}